# Use a Node.js base image
FROM node:22

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy the source files to the container
COPY src /usr/src/app/src
COPY images /usr/src/app/images
COPY files /usr/src/app/files
COPY ./public /usr/src/app/public

# Expose the application port
EXPOSE 3000

# Start the application from the src directory
CMD ["node", "src/app.js"]